# Principal Component Analysis

Principal component analysis is an unsupervised algorithm that attempts to detect the relationship between variables and identify patterns in the data such as X and y features.

If a strong correlation between variables exists, PCA attempt to reduce the dimensionality (size) only makes sense. It's about finding the directions of maximum variance in high-dimensional data and project it onto a smaller dimensional subspace while retaining most of the information.

Basically, PCA is fundamentally a __dimensionality reduction algorithm__ that projects the entire dataset onto a different feature subspace, but it can also be used for other purposes like visualization, noise filtering, and feature extraction and engineering to name some.

#### Goal
Reduce the dimensions of a d-dimensional dataset by projecting it onto a (k)-dimensional subspace (where k<d) in order to increase the computational efficiency while retaining important information.

#### How is k determined?
Compute __eigenvectors__ which are the principal components of a dataset and collect them into a matrix. Each of those eigenvectors is associated with an __eigenvalue__ which can be interpreted as the 'length' or 'magnitude' of the corresponding eigenvector.

#### PCA Approach
- Standardize the data so every features are measured equally
- Compute eigenvetors and eigenvalues pairs from the covariance/correlation matrix or perform singular vector decomposition
- Sort eigenvalues in descending order and choose the _k_ eigenvectors that correspond to the _k_ largest eigenvalues where _k_ is the number of dimensions of the new features subspace (k<=d)
- Construct the projection matrix _W_ from the selected _k_ eigenvectors
- Transform the original dataset _X_ via _W_ to obtain a _k_-dimensional subspace Y

# Problem

1. Can gym (fitness/health) ratings from Google Reviews be predicted using other ratings across other types of categories (food, lifestyle, entertainment)? 

2. Will a model with a dimensionality reduction method applied have better prediction power than one without in this dataset?

## Data
This data set is populated by capturing user ratings from Google reviews. Reviews on attractions from 24 categories across Europe are considered. Google user rating ranges from 1 to 5 and average user rating per category is calculated.

Attribute Information:

- Attribute 1 : Unique user id (removed)
- Attribute 2 : Average ratings on churches 
- Attribute 3 : Average ratings on resorts 
- Attribute 4 : Average ratings on beaches 
- Attribute 5 : Average ratings on parks 
- Attribute 6 : Average ratings on theatres 
- Attribute 7 : Average ratings on museums 
- Attribute 8 : Average ratings on malls 
- Attribute 9 : Average ratings on zoo 
- Attribute 10 : Average ratings on restaurants 
- Attribute 11 : Average ratings on pubs/bars 
- Attribute 12 : Average ratings on local services 
- Attribute 13 : Average ratings on burger/pizza shops 
- Attribute 14 : Average ratings on hotels/other lodgings 
- Attribute 15 : Average ratings on juice bars 
- Attribute 16 : Average ratings on art galleries 
- Attribute 17 : Average ratings on dance clubs 
- Attribute 18 : Average ratings on swimming pools 
- Attribute 19 : Average ratings on gyms (Y)
- Attribute 20 : Average ratings on bakeries 
- Attribute 21 : Average ratings on beauty & spas 
- Attribute 22 : Average ratings on cafes 
- Attribute 23 : Average ratings on view points 
- Attribute 24 : Average ratings on monuments 
- Attribute 25 : Average ratings on gardens

__Characteristics__
- 5,456 rows 
- 24 columns (all numerical)

### Import libraries

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action='ignore')

## Part 1 - Non PCA Modeling

### Import data

Encoding Issue: 

read_csv takes an encoding option to deal with files in different formats.

    In sublime, Click File -> Save with encoding -> UTF-8

    data = pd.read_csv('data.csv', encoding = 'utf-8') # encoding

In [29]:
data = pd.read_csv('Data\\15-google-review-ratings.csv', encoding='utf-8')

In [30]:
data.head()

,Average ratings on churches,Average ratings on resorts,Average ratings on beaches,Average ratings on parks,Average ratings on theatres,Average ratings on museums,Average ratings on malls,Average ratings on zoo,Average ratings on restaurants,Average ratings on pubs/bars,...,Average ratings on art,Average ratings on dance,Average ratings on swimming,Average ratings on gyms,Average ratings on bakeries,Average ratings on beauty spas,Average ratings on cafes,Average ratings on view,Average ratings on monuments,Average ratings on gardens
0,0.0,0.0,3.63,3.65,5.0,2.92,5.0,2.35,2.33,2.64,...,1.74,0.59,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,3.63,3.65,5.0,2.92,5.0,2.64,2.33,2.65,...,1.74,0.59,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,3.63,3.63,5.0,2.92,5.0,2.64,2.33,2.64,...,1.74,0.59,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0
3,0.0,0.5,3.63,3.63,5.0,2.92,5.0,2.35,2.33,2.64,...,1.74,0.59,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,3.63,3.63,5.0,2.92,5.0,2.64,2.33,2.64,...,1.74,0.59,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0

In [31]:
data.describe()

,Average ratings on churches,Average ratings on resorts,Average ratings on beaches,Average ratings on parks,Average ratings on theatres,Average ratings on museums,Average ratings on malls,Average ratings on zoo,Average ratings on restaurants,Average ratings on pubs/bars,...,Average ratings on art,Average ratings on dance,Average ratings on swimming,Average ratings on gyms,Average ratings on bakeries,Average ratings on beauty spas,Average ratings on cafes,Average ratings on view,Average ratings on monuments,Average ratings on gardens
count,5456.000000,5456.000000,5456.000000,5456.000000,5456.000000,5456.00000,5456.000000,5456.000000,5456.000000,5456.000000,...,5456.000000,5456.000000,5456.000000,5456.000000,5456.000000,5456.000000,5456.000000,5456.000000,5456.000000,5455.000000
mean,1.455720,2.319707,2.489331,2.796886,2.958941,2.89349,3.351395,2.540795,3.126019,2.832729,...,2.206573,1.192801,0.949203,0.822414,0.969811,1.000071,0.965838,1.750537,1.531453,1.560755
std,0.827604,1.421438,1.247815,1.309159,1.339056,1.28240,1.413492,1.111391,1.356802,1.307665,...,1.715961,1.107005,0.973536,0.947911,1.203972,1.193891,0.929853,1.598734,1.316889,1.171756
min,0.000000,0.000000,0.000000,0.830000,1.120000,1.11000,1.120000,0.860000,0.840000,0.810000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.920000,1.360000,1.540000,1.730000,1.770000,1.79000,1.930000,1.620000,1.800000,1.640000,...,0.860000,0.690000,0.580000,0.530000,0.520000,0.540000,0.570000,0.740000,0.790000,0.880000
50%,1.340000,1.905000,2.060000,2.460000,2.670000,2.68000,3.230000,2.170000,2.800000,2.680000,...,1.330000,0.800000,0.740000,0.690000,0.690000,0.690000,0.760000,1.030000,1.070000,1.290000
75%,1.810000,2.682500,2.740000,4.092500,4.312500,3.84000,5.000000,3.190000,5.000000,3.530000,...,4.440000,1.160000,0.910000,0.840000,0.860000,0.860000,1.000000,2.070000,1.560000,1.660000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

### Null

In [32]:
# Define a new function
def get_nulls(df):
    
    # Get null pct and counts
    null_cols = pd.DataFrame(df.isnull().sum().sort_values(ascending=False), columns=['Null Data Count'])
    null_cols_pct = pd.DataFrame(round(df.isnull().sum().sort_values(ascending=False)/len(df),2), columns=['Null Data Pct'])

    # Combine dataframes horizontally
    null_cols_df = pd.DataFrame(pd.concat([null_cols, null_cols_pct], axis=1))

    all_nulls = null_cols_df[null_cols_df['Null Data Pct']>0]

    # Print
    print('There are', len(all_nulls), 'columns with missing values.')
    return all_nulls

In [33]:
get_nulls(data)

There are 0 columns with missing values.

Empty DataFrame
Columns: [Null Data Count, Null Data Pct]
Index: []

### X /y Split

In [34]:
# Split training
y = data['Average ratings on gyms']
X = data.drop(['Average ratings on gyms'], axis=1)

### Train / Test Split

In [35]:
# Import split module
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=100)

In [39]:
X_train.describe()

,Average ratings on churches,Average ratings on resorts,Average ratings on beaches,Average ratings on parks,Average ratings on theatres,Average ratings on museums,Average ratings on malls,Average ratings on zoo,Average ratings on restaurants,Average ratings on pubs/bars,...,Average ratings on juice,Average ratings on art,Average ratings on dance,Average ratings on swimming,Average ratings on bakeries,Average ratings on beauty spas,Average ratings on cafes,Average ratings on view,Average ratings on monuments,Average ratings on gardens
count,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,...,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,4092.000000,4091.000000
mean,1.453052,2.330345,2.476860,2.780108,2.950687,2.896860,3.355161,2.555550,3.129174,2.825689,...,2.203121,2.207730,1.197896,0.950978,0.981325,1.014242,0.969980,1.735814,1.528062,1.556392
std,0.826150,1.430383,1.238991,1.300416,1.336791,1.281832,1.412794,1.122755,1.355840,1.310707,...,1.580947,1.713043,1.117127,0.979405,1.218188,1.211068,0.935385,1.586452,1.311276,1.164694
min,0.000000,0.000000,0.000000,0.860000,1.120000,1.110000,1.120000,0.860000,0.840000,0.810000,...,0.760000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.920000,1.370000,1.537500,1.730000,1.770000,1.790000,1.930000,1.620000,1.800000,1.630000,...,1.040000,0.860000,0.690000,0.580000,0.520000,0.540000,0.570000,0.740000,0.790000,0.880000
50%,1.340000,1.910000,2.060000,2.440000,2.670000,2.700000,3.230000,2.200000,2.810000,2.690000,...,1.500000,1.340000,0.800000,0.740000,0.690000,0.690000,0.770000,1.030000,1.070000,1.290000
75%,1.810000,2.700000,2.730000,3.732500,4.310000,3.832500,5.000000,3.200000,5.000000,3.522500,...,2.787500,4.430000,1.160000,0.910000,0.860000,0.870000,1.010000,2.060000,1.572500,1.660000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

### Scaler

In [36]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

# Transform the variables to be on the same scale
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

ValueError: could not convert string to float: '2\t2.'

### Evaluation - RMSE

In [ ]:
# Create a function that will calculate error
def base_rmse(y, y_pred):
    '''
    Return the sqrt of the mean squared error between the observed and predicted values
    '''
    rmse = np.sqrt(mean_squared_error(y, y_pred))
    return rmse

### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error 

# Random Forest
model = RandomForestRegressor(n_estimators=500, random_state=10)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
rf_rmse = base_rmse(y_test, y_pred)
print('Random Forest RMSE: {:.2f}'.format(rf_rmse))

### Feature Importance

In [ ]:
headers = X.columns

# Create a new function to capture feature importance for free models (RF, GB, XGB)
def feature_importance(model):
    
    importance = pd.DataFrame({'Feature': headers,
                               'Importance': np.round(model.feature_importances_,5)})
    
    importance = importance.sort_values(by='Importance', ascending=False).set_index('Feature')
    
    return importance

In [ ]:
feature_importance(model)

## Part 2 - PCA Modeling